create DATABASE Randart;

Use Randart;
Insert into Pais (Descripcion) values ('Afganistán');
Insert into Pais (Descripcion) values ('Åland');
Insert into Pais (Descripcion) values ('Albania');
Insert into Pais (Descripcion) values ('Alemania');
Insert into Pais (Descripcion) values ('Andorra');
Insert into Pais (Descripcion) values ('Angola');
Insert into Pais (Descripcion) values ('Anguilla');
Insert into Pais (Descripcion) values ('Antártida');
Insert into Pais (Descripcion) values ('Antigua y Barbuda');
Insert into Pais (Descripcion) values ('Antillas Holandesas');
Insert into Pais (Descripcion) values ('Arabia Saudita');
Insert into Pais (Descripcion) values ('Argelia');
Insert into Pais (Descripcion) values ('Argentina');
Insert into Pais (Descripcion) values ('Armenia');
Insert into Pais (Descripcion) values ('Aruba');
Insert into Pais (Descripcion) values ('Australia');
Insert into Pais (Descripcion) values ('Austria');
Insert into Pais (Descripcion) values ('Azerbaiyán');
Insert into Pais (Descripcion) values ('Bahamas');
Insert into Pais (Descripcion) values ('Banglades');
Insert into Pais (Descripcion) values ('Barbados');
Insert into Pais (Descripcion) values ('Baréin');
Insert into Pais (Descripcion) values ('Bélgica');
Insert into Pais (Descripcion) values ('Belice');
Insert into Pais (Descripcion) values ('Benin');
Insert into Pais (Descripcion) values ('Bermudas');
Insert into Pais (Descripcion) values ('Bielorrusia');
Insert into Pais (Descripcion) values ('Birmania');
Insert into Pais (Descripcion) values ('Bolivia');
Insert into Pais (Descripcion) values ('Bosnia-Herzegovina');
Insert into Pais (Descripcion) values ('Botsuana');
Insert into Pais (Descripcion) values ('Brasil');
Insert into Pais (Descripcion) values ('Brunei');
Insert into Pais (Descripcion) values ('Bulgaria');
Insert into Pais (Descripcion) values ('Burkina Faso');
Insert into Pais (Descripcion) values ('Burundi');
Insert into Pais (Descripcion) values ('Butan');
Insert into Pais (Descripcion) values ('Cabo Verde');
Insert into Pais (Descripcion) values ('Camboya');
Insert into Pais (Descripcion) values ('Camerún');
Insert into Pais (Descripcion) values ('Canadá');
Insert into Pais (Descripcion) values ('Chad');
Insert into Pais (Descripcion) values ('Chequia');
Insert into Pais (Descripcion) values ('Chile');
Insert into Pais (Descripcion) values ('China');
Insert into Pais (Descripcion) values ('Chipre');
Insert into Pais (Descripcion) values ('Ciudad del Vaticano');
Insert into Pais (Descripcion) values ('Colombia');
Insert into Pais (Descripcion) values ('Comoras');
Insert into Pais (Descripcion) values ('Congo');
Insert into Pais (Descripcion) values ('Corea del Norte');
Insert into Pais (Descripcion) values ('Corea del Sur');
Insert into Pais (Descripcion) values ('Costa de Marfil');
Insert into Pais (Descripcion) values ('Costa Rica');
Insert into Pais (Descripcion) values ('Croacia');
Insert into Pais (Descripcion) values ('Cuba');
Insert into Pais (Descripcion) values ('Dinamarca');
Insert into Pais (Descripcion) values ('Dominica');
Insert into Pais (Descripcion) values ('Ecuador');
Insert into Pais (Descripcion) values ('Egipto');
Insert into Pais (Descripcion) values ('El Salvador');
Insert into Pais (Descripcion) values ('Emiratos Árabes Unidos');
Insert into Pais (Descripcion) values ('Eritrea');
Insert into Pais (Descripcion) values ('Eslovaquia');
Insert into Pais (Descripcion) values ('Eslovenia');
Insert into Pais (Descripcion) values ('España');
Insert into Pais (Descripcion) values ('Estado de Palestina');
Insert into Pais (Descripcion) values ('Estados Federados de Micronesia');
Insert into Pais (Descripcion) values ('Estados Unidos');
Insert into Pais (Descripcion) values ('Estonia');
Insert into Pais (Descripcion) values ('Etiopía');
Insert into Pais (Descripcion) values ('Filipinas');
Insert into Pais (Descripcion) values ('Finlandia');
Insert into Pais (Descripcion) values ('Fiyi');
Insert into Pais (Descripcion) values ('Francia');
Insert into Pais (Descripcion) values ('Gabón');
Insert into Pais (Descripcion) values ('Gambia');
Insert into Pais (Descripcion) values ('Georgia');
Insert into Pais (Descripcion) values ('Ghana');
Insert into Pais (Descripcion) values ('Gibraltar');
Insert into Pais (Descripcion) values ('Granada');
Insert into Pais (Descripcion) values ('Grecia');
Insert into Pais (Descripcion) values ('Groenlandia');
Insert into Pais (Descripcion) values ('Guadalupe');
Insert into Pais (Descripcion) values ('Guam');
Insert into Pais (Descripcion) values ('Guatemala');
Insert into Pais (Descripcion) values ('Guayana Francesa');
Insert into Pais (Descripcion) values ('Guernsey');
Insert into Pais (Descripcion) values ('Guinea');
Insert into Pais (Descripcion) values ('Guinea Ecuatorial');
Insert into Pais (Descripcion) values ('Guinea-Bisau');
Insert into Pais (Descripcion) values ('Guyana');
Insert into Pais (Descripcion) values ('Haití');
Insert into Pais (Descripcion) values ('Holanda');
Insert into Pais (Descripcion) values ('Honduras');
Insert into Pais (Descripcion) values ('Hong Kong');
Insert into Pais (Descripcion) values ('Hungría');
Insert into Pais (Descripcion) values ('India');
Insert into Pais (Descripcion) values ('Indonesia');
Insert into Pais (Descripcion) values ('Irán');
Insert into Pais (Descripcion) values ('Iraq');
Insert into Pais (Descripcion) values ('Irlanda');
Insert into Pais (Descripcion) values ('Isla de Man');
Insert into Pais (Descripcion) values ('Isla de Navidad');
Insert into Pais (Descripcion) values ('Isla de San Martín');
Insert into Pais (Descripcion) values ('Islandia');
Insert into Pais (Descripcion) values ('IslaNorfolk');
Insert into Pais (Descripcion) values ('Islas Caimán');
Insert into Pais (Descripcion) values ('Islas Cocos');
Insert into Pais (Descripcion) values ('Islas Cook');
Insert into Pais (Descripcion) values ('Islas Feroe');
Insert into Pais (Descripcion) values ('Islas Malvinas');
Insert into Pais (Descripcion) values ('Islas Marshall');
Insert into Pais (Descripcion) values ('Islas Pitcairn');
Insert into Pais (Descripcion) values ('Islas Salomón');
Insert into Pais (Descripcion) values ('Islas Turcas y Caicos');
Insert into Pais (Descripcion) values ('Islas Vírgenes Británicas');
Insert into Pais (Descripcion) values ('Islas Vírgenes de los Estados Unidos');
Insert into Pais (Descripcion) values ('IslasMarianasdelNorte');
Insert into Pais (Descripcion) values ('Israel');
Insert into Pais (Descripcion) values ('Italia');
Insert into Pais (Descripcion) values ('Jamaica');
Insert into Pais (Descripcion) values ('Japón');
Insert into Pais (Descripcion) values ('Jersey');
Insert into Pais (Descripcion) values ('Jordania');
Insert into Pais (Descripcion) values ('Kazajistán');
Insert into Pais (Descripcion) values ('Kenia');
Insert into Pais (Descripcion) values ('Kirguistán');
Insert into Pais (Descripcion) values ('Kiribati');
Insert into Pais (Descripcion) values ('Kosovo');
Insert into Pais (Descripcion) values ('Kuwait');
Insert into Pais (Descripcion) values ('Laos');
Insert into Pais (Descripcion) values ('Lesoto');
Insert into Pais (Descripcion) values ('Letonia');
Insert into Pais (Descripcion) values ('Líbano');
Insert into Pais (Descripcion) values ('Liberia');
Insert into Pais (Descripcion) values ('Libia');
Insert into Pais (Descripcion) values ('Liechtenstein');
Insert into Pais (Descripcion) values ('Lituania');
Insert into Pais (Descripcion) values ('Luxemburgo');
Insert into Pais (Descripcion) values ('Macao');
Insert into Pais (Descripcion) values ('Madagascar');
Insert into Pais (Descripcion) values ('Malasia');
Insert into Pais (Descripcion) values ('Malaui');
Insert into Pais (Descripcion) values ('Maldivas');
Insert into Pais (Descripcion) values ('Malí');
Insert into Pais (Descripcion) values ('Malta');
Insert into Pais (Descripcion) values ('Marruecos');
Insert into Pais (Descripcion) values ('Martinica');
Insert into Pais (Descripcion) values ('Mauricio');
Insert into Pais (Descripcion) values ('Mauritania');
Insert into Pais (Descripcion) values ('Mayotte');
Insert into Pais (Descripcion) values ('México');
Insert into Pais (Descripcion) values ('Moldavia');
Insert into Pais (Descripcion) values ('Monaco');
Insert into Pais (Descripcion) values ('Mongolia');
Insert into Pais (Descripcion) values ('Montenegro');
Insert into Pais (Descripcion) values ('Montserrat');
Insert into Pais (Descripcion) values ('Mozambique');
Insert into Pais (Descripcion) values ('Namibia');
Insert into Pais (Descripcion) values ('Nauru');
Insert into Pais (Descripcion) values ('Nepal');
Insert into Pais (Descripcion) values ('Nicaragua');
Insert into Pais (Descripcion) values ('Niger');
Insert into Pais (Descripcion) values ('Nigeria');
Insert into Pais (Descripcion) values ('Niue');
Insert into Pais (Descripcion) values ('Noruega');
Insert into Pais (Descripcion) values ('Nueva Caledonia');
Insert into Pais (Descripcion) values ('Nueva Zelanda');
Insert into Pais (Descripcion) values ('Omán');
Insert into Pais (Descripcion) values ('Pakistán');
Insert into Pais (Descripcion) values ('Palaos');
Insert into Pais (Descripcion) values ('Panamá');
Insert into Pais (Descripcion) values ('Papúa Nueva Guinea');
Insert into Pais (Descripcion) values ('Paraguay');
Insert into Pais (Descripcion) values ('Perú');
Insert into Pais (Descripcion) values ('Polinesia Francesa');
Insert into Pais (Descripcion) values ('Polonia');
Insert into Pais (Descripcion) values ('Portugal');
Insert into Pais (Descripcion) values ('Puerto Rico');
Insert into Pais (Descripcion) values ('Qatar');
Insert into Pais (Descripcion) values ('Reino Unido');
Insert into Pais (Descripcion) values ('República Centroafricana');
Insert into Pais (Descripcion) values ('República de Macedonia');
Insert into Pais (Descripcion) values ('República Democrática del Congo');
Insert into Pais (Descripcion) values ('República Dominicana');
Insert into Pais (Descripcion) values ('Reunion');
Insert into Pais (Descripcion) values ('Ruanda');
Insert into Pais (Descripcion) values ('Rumania');
Insert into Pais (Descripcion) values ('Rusia');
Insert into Pais (Descripcion) values ('Samoa');
Insert into Pais (Descripcion) values ('Samoa Americana');
Insert into Pais (Descripcion) values ('San Bartolome');
Insert into Pais (Descripcion) values ('San Cristóbal y Nieves');
Insert into Pais (Descripcion) values ('San Marino');
Insert into Pais (Descripcion) values ('San Pedro y Miquelon');
Insert into Pais (Descripcion) values ('San Vicente y las Granadinas');
Insert into Pais (Descripcion) values ('Santa Elena, Ascensión y Tristán de Acuña');
Insert into Pais (Descripcion) values ('Santa Lucía');
Insert into Pais (Descripcion) values ('Santo Tomé y Príncipe');
Insert into Pais (Descripcion) values ('Senegal');
Insert into Pais (Descripcion) values ('Serbia');
Insert into Pais (Descripcion) values ('Seychelles');
Insert into Pais (Descripcion) values ('Sierra Leona');
Insert into Pais (Descripcion) values ('Singapur');
Insert into Pais (Descripcion) values ('Siria');
Insert into Pais (Descripcion) values ('Somalia');
Insert into Pais (Descripcion) values ('Sri Lanka');
Insert into Pais (Descripcion) values ('Suazilandia');
Insert into Pais (Descripcion) values ('Sudáfrica');
Insert into Pais (Descripcion) values ('Sudán');
Insert into Pais (Descripcion) values ('Sudán del Sur');
Insert into Pais (Descripcion) values ('Suecia');
Insert into Pais (Descripcion) values ('Suiza');
Insert into Pais (Descripcion) values ('Surinam');
Insert into Pais (Descripcion) values ('Svalbard y Jan Mayen');
Insert into Pais (Descripcion) values ('Tailandia');
Insert into Pais (Descripcion) values ('Taiwán');
Insert into Pais (Descripcion) values ('Tanzania');
Insert into Pais (Descripcion) values ('Tayikistán');
Insert into Pais (Descripcion) values ('Territorio Británico del Océano Índico');
Insert into Pais (Descripcion) values ('Timor Oriental');
Insert into Pais (Descripcion) values ('Togo');
Insert into Pais (Descripcion) values ('Tokelau');
Insert into Pais (Descripcion) values ('Tonga');
Insert into Pais (Descripcion) values ('Trinidad y Tobago');
Insert into Pais (Descripcion) values ('Túnez');
Insert into Pais (Descripcion) values ('Turkmenistán');
Insert into Pais (Descripcion) values ('Turquía');
Insert into Pais (Descripcion) values ('Tuvalu');
Insert into Pais (Descripcion) values ('Ucrania');
Insert into Pais (Descripcion) values ('Uganda');
Insert into Pais (Descripcion) values ('Uruguay');
Insert into Pais (Descripcion) values ('Uzbekistán');
Insert into Pais (Descripcion) values ('Vanuatu');
Insert into Pais (Descripcion) values ('Venezuela');
Insert into Pais (Descripcion) values ('Vietnam');
Insert into Pais (Descripcion) values ('Wallis y Futuna');
Insert into Pais (Descripcion) values ('Yemen');
Insert into Pais (Descripcion) values ('Yibuti');
Insert into Pais (Descripcion) values ('Zambia');
Insert into Pais (Descripcion) values ('Zimbabue');

